game: Sons of The Forest
usewine: true
usex: true
steamid: 2465200
backupdir: /backups/current/Saves/
configs:
  "config/dedicatedserver.cfg": "/backups/current/dedicatedserver.cfg"
  "config/ownerswhitelist.txt": "/backups/current/ownerswhitelist.txt"
