game: Sons of The Forest
usewine: true
usex: true
steamid: 2465200
configs:
  "config/dedicatedserver.cfg": "/config/dedicatedserver.cfg"
  "config/ownerswhitelist.txt": "/config/ownerswhitelist.txt"
