game: Sons of The Forest
usewine: true
usex: true
steamid: 2465200
configs:
  "config/dedicatedserver.cfg": "/userdata/dedicatedserver.cfg"
  "config/ownerswhitelist.txt": "/userdata/ownerswhitelist.txt"
