#!/command/with-contenv bash

while true; do

  sleep 3600

  if [  -f "/gameservers/$GAMESERVER/backup.sh" ]; then
    echo "Backup up $GAMESERVER"
    /gameservers/$GAMESERVER/backup.sh
  fi

  # prune old backups
  ls -1t /backups/ | tail -n +5 | xargs -r rm --

done
