#!/command/with-contenv bash

mkdir -p /backups
while true; do

  sleep $BIPOPS_BACKUP_INTERVAL

  if [  -f "/gameservers/$BIPOPS_GAMESERVER/backup.sh" ]; then
    echo "Backup up $BIPOPS_GAMESERVER"
    s6-setuidgid bipops /gameservers/$BIPOPS_GAMESERVER/backup.sh
  fi

  # prune old backups
  ls -1t /backups/ | tail -n +5 | xargs -r rm --

done
