game: Palworld
usewine: false
usex: false
steamid: 2394010
configs:
  "config/PalWorldSettings.ini": "/game/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini"
  "config/Engine.ini": "/game/Pal/Saved/Config/LinuxServer/Engine.ini"